// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgGxKikA4cvVZOIZ_KX1nJHjjlKfKyy9A',
    appId: '1:464696298905:android:e1dada9ffd6924434dd708',
    messagingSenderId: '464696298905',
    projectId: 'lifestylez2255',
    storageBucket: 'lifestylez2255.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGgtlffDE13OKU61aPREYWITKpyZNtGs',
    appId: '1:129474244975:ios:7ab5af7422b12321f7f89a',
    messagingSenderId: '129474244975',
    projectId: 'fir-auth-9562e',
    storageBucket: 'fir-auth-9562e.firebasestorage.app',
    iosBundleId: 'com.example.projectEcommerce',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJd1Z-hY1tRLBmJ5OcCOR2LNSMqBhR9tY',
    appId: '1:129474244975:web:6627067d74a2e13ef7f89a',
    messagingSenderId: '129474244975',
    projectId: 'fir-auth-9562e',
    authDomain: 'fir-auth-9562e.firebaseapp.com',
    storageBucket: 'fir-auth-9562e.firebasestorage.app',
    measurementId: 'G-Z313SXCTZD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRGgtlffDE13OKU61aPREYWITKpyZNtGs',
    appId: '1:129474244975:ios:7ab5af7422b12321f7f89a',
    messagingSenderId: '129474244975',
    projectId: 'fir-auth-9562e',
    storageBucket: 'fir-auth-9562e.firebasestorage.app',
    iosBundleId: 'com.example.projectEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJd1Z-hY1tRLBmJ5OcCOR2LNSMqBhR9tY',
    appId: '1:129474244975:web:b5932c3ee9e015c6f7f89a',
    messagingSenderId: '129474244975',
    projectId: 'fir-auth-9562e',
    authDomain: 'fir-auth-9562e.firebaseapp.com',
    storageBucket: 'fir-auth-9562e.firebasestorage.app',
    measurementId: 'G-6TQJB43SM7',
  );

}